### ISSUE TITLE
CI funktioniert nicht.

### ISSUE THREAD

**Issue by martins-1992** [minova-afis/aero.minova.spring.maven.root#22]
Dieser Fehler war auch vor der CI-Anpassung aufgetaucht: https://github.com/minova-afis/aero.minova.spring.maven.root/commit/c504a3fec3e29bcc2edcee06c3b4839a8f2b272a .
Zudem ist der neue Workflow identisch zu https://github.com/minova-afis/aero.minova.github.workflows.utils ,
wo das Problem nicht auftaucht.

**Comment by scholz-afis** [comment]
@martins-1992 Du versuchst nicht zufällig Workflows von einem **privaten** Repository in diesem **public** Repository zu verwenden? Das geht nicht, jedoch kannst Du unsere Workflows in einem **public** Repo freigeben und verhindern, dass diese Flows jemand anders benutzt: https://www.teracloud.io/single-post/github-reusable-workflows

**Comment by martins-1992** [comment]
Habe nicht gemerkt, dass `maven.root` public is.

**Comment by scholz-afis** [comment]
Ich habe nun auf *common Workflows* umgestellt:
* [Build Workflow](https://github.com/minova-afis/aero.minova.spring.maven.root/actions/runs/5935713256) geht 
* [Release Workflow](https://github.com/minova-afis/aero.minova.spring.maven.root/actions/runs/5935853253) geht, [Package](https://github.com/minova-afis/aero.minova.maven.root/packages/157663) 

@martins-1992 Ist hier noch mehr zu tun, oder würdest Du das Issue schließen?

**Comment by martins-1992** [comment]
Ja, die CI funktioniert inzwischen mit den public Workflows.
Danke für das Umsetzen.
Ich hatte das Thema nicht mehr auf dem Schirm.
